import { Component, OnInit, EventEmitter, Output } from '@angular/core'; // eventemitted and output added for add todo function onSubmit()

@Component({
    selector: 'app-add-todo',
    templateUrl: './add-todo.component.html',
    styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent implements OnInit {
    @Output() addTodo: EventEmitter<any> = new EventEmitter(); // use any because we don't have an id yet to match the model
    
    title: string;

    constructor() { }

    ngOnInit(): void {
    }

    // triggered from add-todo.component.html submit button for add todo
    onSubmit() {
        const todo = { // id will be generated by api
            title: this.title,
            completed: false // default completed to false because you just made the todo.
        }
        this.addTodo.emit(todo);
    }

}
